require 'json'
require 'open3'

def node_require(script)
  require Pod::Executable.execute_command('node', [
    '-p',
    "require.resolve('#{script}', {paths: ['#{__dir__}']})"
  ]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

permissions_path = '../node_modules/react-native-permissions/ios'
platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'LocationAccuracy','LocationAlways','LocationWhenInUse'
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'GoBoozePartner' do
  config = use_native_modules!
  
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'GoBoozePartnerTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
